# -*- coding: utf-8 -*-
"""Central registry for Calculate Circuits alert definitions."""

from CEDElectrical.Model.alert_definition import AlertDefinition


ALERT_DEFINITIONS = {
    "overrides_invalid_circuit_property": AlertDefinition(
        "Overrides.InvalidCircuitProperty",
        "User-specified {property} '{override_value}' invalid; Using default {property}: {default_value}",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "overrides_invalid_wire_sets": AlertDefinition(
        "Overrides.InvalidWireSets",
        "User-specified wire sets '{override_value}' invalid; using default wire sets: {default_value}",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "overrides_invalid_equipment_ground": AlertDefinition(
        "Overrides.InvalidEquipmentGround",
        "User-specified equipment ground size '{override_value}' invalid; sizing per NEC Table 250.122",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "overrides_invalid_service_ground": AlertDefinition(
        "Overrides.InvalidServiceGround",
        "User-specified service ground size '{override_value}' invalid; sizing per NEC Table 250.102(c)",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "overrides_invalid_hot_wire": AlertDefinition(
        "Overrides.InvalidHotWire",
        "User-specified wire size '{override_value}' invalid; returning calculated value instead.",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "overrides_invalid_conduit": AlertDefinition(
        "Overrides.InvalidConduit",
        "User-specified conduit size '{override_value}' invalid; returning calculated value instead.",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "design_non_standard_ocp_rating": AlertDefinition(
        "Design.NonStandardOCPRating",
        "Overcurrent Device has non-standard ampere rating ({breaker_size}A) per NEC Table 240.6(A).",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_breaker_lug_size_limit_override": AlertDefinition(
        "Design.BreakerLugSizeLimitOverride",
        "User-specified Hot size {hot_size} exceeds recommended maximum for {breaker_size}A Breaker ({max_lug_size}).",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_breaker_lug_quantity_limit_override": AlertDefinition(
        "Design.BreakerLugQuantityLimitOverride",
        "User-specified wire sets ({wire_sets} sets) exceeds recommended maximum for {breaker_size}A Breaker ({max_lug_qty} sets).",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "calculation_breaker_lug_size_limit": AlertDefinition(
        "Calculations.BreakerLugSizeLimit",
        "Calculated Hot Size #{hot_size} exceeds recommended maximum for breaker size {breaker_size}A.",
        group="Calculation",
        severity="MEDIUM",
        category="Circuits",
    ),
    "calculation_breaker_lug_quantity_limit": AlertDefinition(
        "Calculations.BreakerLugQuantityLimit",
        "Calculated wire sets ({wire_sets} sets) exceeds recommended maximum for breaker size {breaker_size}A.",
        group="Calculation",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_excessive_conduit_fill": AlertDefinition(
        "Design.ExcessiveConduitFill",
        "User-specified conduit size {conduit_size} exceeds max fill target ({conduit_fill_percentage}% > {max_fill_percentage}%).",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_undersized_wire_egc": AlertDefinition(
        "Design.UndersizedWireEGC",
        "User-specified ground size ({ground_size} {wire_material}) does not meet required size per NEC 250.122.",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_undersized_wire_service_ground": AlertDefinition(
        "Design.UndersizedWireServiceGround",
        "User-specified ground size ({ground_size} {wire_material}) does not meet required size per NEC 250.102.",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_excessive_volt_drop": AlertDefinition(
        "Design.ExcessiveVoltDrop",
        "User-specified wire ({wire_sets} set(s) x {wire_size}) fails volt drop check ({vd_percent}%).",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_insufficient_ampacity": AlertDefinition(
        "Design.InsufficientAmpacity",
        "User-specified wire ({wire_sets} set(s) x {wire_size}) fails ampacity check (Ampacity: {circuit_ampacity}A, Circuit Load: {circuit_load_current}A)",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_insufficient_ampacity_breaker": AlertDefinition(
        "Design.InsufficientAmpacityBreaker",
        "User-specified wire ({wire_sets} set(s) x {wire_size}) fails breaker ampacity check (Ampacity: {circuit_ampacity}A, Breaker: {breaker_rating}A)",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_undersized_ocp": AlertDefinition(
        "Design.UndersizedOCP",
        "Circuit load current ({circuit_load_current}A) exceeds User-specified breaker rating ({breaker_rating}A)",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_near_ocp_rating": AlertDefinition(
        "Design.NearOCPRating",
        "Circuit load current ({circuit_load_current}A) is within {load_ratio_percent}% of User-specified breaker rating ({breaker_rating}A)",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "design_circuit_loads_null": AlertDefinition(
        "Design.CircuitLoadsNull",
        "Power Circuit Connected to a panel has a 0 A load.",
        group="Design",
        severity="MEDIUM",
        category="Circuits",
    ),
    "design_circuit_panels_null": AlertDefinition(
        "Design.CircuitPanelsNull",
        "Circuit with a non-zero load is NOT connected to a panel.",
        group="Design",
        severity="HIGH",
        category="Circuits",
    ),
    "overrides_invalid_isolated_ground": AlertDefinition(
        "Overrides.InvalidIsolatedGround",
        "User-specified isolated ground size '{override_value}' invalid; using equipment ground size instead.",
        group="Overrides",
        severity="NONE",
        persistent=False,
        category="Circuits",
    ),
    "calculation_wire_sizing_failed": AlertDefinition(
        "Calculations.WireSizingFailed",
        "Unable to automatically calculate wire sizing: {reason}",
        group="Calculation",
        severity="CRITICAL",
        category="Circuits",
    ),
    "calculation_conduit_sizing_failed": AlertDefinition(
        "Calculations.ConduitSizingFailed",
        "Unable to automatically calculate conduit size for fill {fill_ratio}% at max fill {max_fill}%.",
        group="Calculation",
        severity="CRITICAL",
        category="Circuits",
    ),
    "qc_circuit_rating_below_current": AlertDefinition(
        "QC.Circuit.RatingBelowCurrent",
        "Circuit rating is below apparent current.",
        group="QC",
        severity="HIGH",
        category="Circuits",
    ),
    "qc_device_load_not_connected": AlertDefinition(
        "QC.Device.LoadNotConnected",
        "Non-zero load is not connected to an electrical system.",
        group="QC",
        severity="HIGH",
        category="Devices",
    ),
    "qc_device_load_no_panel": AlertDefinition(
        "QC.Device.LoadNoPanel",
        "Non-zero load circuit is not assigned to a panel.",
        group="QC",
        severity="HIGH",
        category="Devices",
    ),
    "qc_equipment_mains_below_demand": AlertDefinition(
        "QC.Equipment.MainsBelowDemand",
        "Equipment mains rating is below total demand current.",
        group="QC",
        severity="HIGH",
        category="Panels/Switchgear",
    ),
    "qc_equipment_mcb_below_demand": AlertDefinition(
        "QC.Equipment.McbBelowDemand",
        "Equipment MCB rating is below total demand current.",
        group="QC",
        severity="HIGH",
        category="Panels/Switchgear",
    ),
    "qc_transformer_rating_missing": AlertDefinition(
        "QC.Transformer.RatingMissing",
        "Transformer rating parameter is missing.",
        group="QC",
        severity="INFO",
        category="Transformers",
    ),
    "qc_transformer_demand_exceeds_rating": AlertDefinition(
        "QC.Transformer.DemandExceedsRating",
        "Transformer demand exceeds transformer kVA rating.",
        group="QC",
        severity="HIGH",
        category="Transformers",
    ),
    "qc_transformer_primary_demand_near_breaker": AlertDefinition(
        "QC.Transformer.PrimaryDemandNearBreaker",
        "Transformer primary demand current is near upstream breaker rating.",
        group="QC",
        severity="MEDIUM",
        category="Transformers",
    ),
    "qc_transformer_primary_rating_near_breaker": AlertDefinition(
        "QC.Transformer.PrimaryRatingNearBreaker",
        "Transformer rated primary current is near upstream breaker rating.",
        group="QC",
        severity="MEDIUM",
        category="Transformers",
    ),
    "qc_transformer_secondary_length_over_25ft": AlertDefinition(
        "QC.Transformer.SecondaryLengthOver25Ft",
        "Transformer secondary circuit length exceeds 25 feet.",
        group="QC",
        severity="MEDIUM",
        category="Transformers",
    ),
    "qc_equipment_mcb_exceeds_mains": AlertDefinition(
        "QC.Equipment.McbExceedsMains",
        "Equipment MCB rating exceeds equipment mains rating.",
        group="QC",
        severity="HIGH",
        category="Panels/Switchgear",
    ),
    "qc_equipment_supply_breaker_exceeds_mains": AlertDefinition(
        "QC.Equipment.SupplyBreakerExceedsMains",
        "Upstream breaker exceeds downstream equipment mains rating.",
        group="QC",
        severity="MEDIUM",
        category="Panels/Switchgear",
    ),
    "qc_equipment_supply_breaker_exceeds_mcb": AlertDefinition(
        "QC.Equipment.SupplyBreakerExceedsMcb",
        "Upstream breaker exceeds downstream equipment MCB rating.",
        group="QC",
        severity="INFO",
        category="Panels/Switchgear",
    ),
    "qc_equipment_mcb_exceeds_supply_breaker": AlertDefinition(
        "QC.Equipment.McbExceedsSupplyBreaker",
        "Downstream MCB exceeds upstream breaker rating.",
        group="QC",
        severity="MEDIUM",
        category="Panels/Switchgear",
    ),
    "qc_panel_open_slots": AlertDefinition(
        "QC.Panel.OpenSlots",
        "Panel has open slots.",
        group="QC",
        severity="INFO",
        category="Panels/Switchgear",
    ),
    "qc_panel_supplies_larger_equipment": AlertDefinition(
        "QC.Panel.SuppliesLargerEquipment",
        "Panel appears to supply equipment with a larger rating than the source panel.",
        group="QC",
        severity="MEDIUM",
        category="Panels/Switchgear",
    ),
}
